# Generated by Django 4.2.7 on 2023-12-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_usercustom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCustom',
            new_name='UserProfile',
        ),
    ]
